CREATE TABLE survey_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answers JSONB NOT NULL,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  can_contact BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add a policy to enable row-level security
ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows inserting data for authenticated and anonymous users
CREATE POLICY "Allow anonymous inserts" ON survey_responses FOR INSERT TO anon WITH CHECK (true);

-- Grant necessary permissions to the anon role
GRANT INSERT ON survey_responses TO anon;